version: '3.8'

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:v4
    container_name: lavalink
    restart: always
    # entrypoint: ["java", "-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2", "-Xmx6G", "-jar", "Lavalink.jar"]
    environment:
      # - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass 
    volumes:
      - ./LavalinkServer/logs/:/opt/Lavalink/logs/  # run `sudo chown -R 322:322 logs`
      - ./LavalinkServer/plugins/:/opt/Lavalink/plugins/  # run `sudo chown -R 322:322 plugins`
      - ./LavalinkServer/application.yml:/opt/Lavalink/application.yml
    expose:
      - 2333
    ports:
      - 2333:2333

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    depends_on:
      - lavalink
    volumes:
      - ./logs:/logs
    restart: always
    