version: '3.8'

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4.0.0
    container_name: bot-lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass 
    volumes:
      - ./Lavalink/logs/:/opt/Lavalink/logs/  # run `sudo chown -R 322:322 logs`
      - ./Lavalink/plugins/:/opt/Lavalink/plugins/  # run `sudo chown -R 322:322 plugins`
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
      - 2333:2333

  # redis:
  #   image: 'bitnami/redis:latest'
  #   container_name: bot-redis
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - 6379:6379
  #   restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MusicCat
    depends_on:
      - lavalink
      # - redis
    volumes:
      - ./logs:/logs
    restart: unless-stopped
    