version: '3.8'

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:v4-update-lp
    container_name: Lavalink
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass 
    volumes:
      - ./Lavalink/logs/:/opt/Lavalink/logs/  # run `sudo chown -R 322:322 logs`
      - ./Lavalink/plugins/:/opt/Lavalink/plugins/  # run `sudo chown -R 322:322 plugins`
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
      - 2333:2333
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MusicCat
    depends_on:
      - lavalink
    volumes:
      - ./logs:/logs
    restart: unless-stopped
    