version: '2.15'

services:
  lavalink:
    build:
      context: ./LavalinkServer
      dockerfile: Dockerfile
    volumes:
      - ./LavalinkServer/logs:/logs
    expose:
      - 2333
    restart: always

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - lavalink
    volumes:
      - ./logs:/logs
    restart: always
